### ISSUE TITLE
practica

### ISSUE THREAD

**Issue by lourdeshernandez2003** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-lourdeshernandez2003#1]
[Practica-Maria de lourdes Hernandez Hernandez..pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-lourdeshernandez2003/files/7151471/Practica-Maria.de.lourdes.Hernandez.Hernandez.pdf)

**Comment by lucero012** [comment]
un 20% porque cumples lo pedido en la rubrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
